/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "PoolMiner_Lite.hpp"

std::string PoolMiner_Lite::Greeter::greeting() {
    return std::string("Hello, World!");
}
