/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef POOLMINER_LITE_H
#define POOLMINER_LITE_H

#ifdef _WIN32
#define POOLMINER_LITE_EXPORT_FUNC __declspec(dllexport)
#else
#define POOLMINER_LITE_EXPORT_FUNC
#endif

#include <string>

namespace PoolMiner_Lite {
    class Greeter {
        public:
        std::string POOLMINER_LITE_EXPORT_FUNC greeting();
    };
}

#endif
