name: Auto-Test

on:
  push:
    paths:
      - 'core/**'
      - 'android/**'

permissions:
  actions: write
  contents: write

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.changes.outputs.core }}
      android: ${{ steps.changes.outputs.android }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: File Check
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            core:
              - 'core/**'
            android:
              - 'android/**'

  core-test:
    runs-on: ubuntu-latest
    needs: check-changes
    if: ${{ needs.check-changes.outputs.core == 'true' }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check Changes
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          list-files: shell
          filters: |
            core-src:
              - added|modified: 'core/**/*.cpp'
              - added|modified: 'core/**/*.hpp'

      - name: Format Code C++
        if: ${{ steps.changes.outputs.core-src == 'true' }}
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          sudo apt-get install -y clang-format
          echo ${{ steps.changes.outputs.core-src }} | xargs -n 1 clang-format -i
          git add .
          git commit -m "Core Reformatting Sources"

      - name: Publish in github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Core Check
        run: gradle :core:check

  android-build:
    runs-on: ubuntu-latest
    needs: [check-changes, core-test]
    if: ${{ (needs.check-changes.outputs.android == 'true') && ((needs.check-changes.outputs.core == 'false') || success()) }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check Changes
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            android-java:
              - added|modified: 'android/src/**/*.java'

      - name: Setup Java 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Format Java Code
      	if: ${{ steps.changes.outputs.android-java == 'true' }}
        uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          files: "android/src/**/*.java"
          args: "-r -a"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Android Build
        run: gradle :android:build -Prelease

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: APK
          path: ${{ github.workspace }}/android/build/outputs/apk/release/android-release.apk

