name: Auto-Test

on:
  push:
    paths:
      - 'core/**'
      - 'android/**'

permissions:
  actions: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            ifcore:
              - 'core/**'
            ifandroid:
              - 'android/**'

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Core Check
        if: steps.changes.outputs.ifcore == 'true'
        run: gradle :core:check

      - name: Commit changes File
        run: |
          gradle spotlessApply
          gradle spotlessCheck
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          git add .
          git commit -m "changes of formating"

      - name: Publish in github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Android Build
        if: steps.changes.outputs.ifandroid == 'true'
        run: gradle :android:build -Prelease

      - name: Upload Android
        if: steps.changes.outputs.ifandroid == 'true'
        uses: actions/upload-artifact@v4.3.3
        with:
          name: APK
          path: ${{ github.workspace }}/android/build/outputs/apk/release/android-release.apk

