name: Auto-Test

on:
  push:
    paths:
      - '.github/workflows/auto.yml'
      - 'core/**'
      - 'android/**'

jobs:
  core:
    runs-on: ubuntu-latest
    outputs:
      android: ${{ steps.changes.outputs.android }}
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            core:
              - 'core/**'
            android:
              - 'android/**'
            c-src:
              - added|modified: 'core/**/*.c'
              - added|modified: 'core/**/*.h'
              - added|modified: 'android/src/main/c/**/*.c'
            android-java:
              - added|modified: 'android/src/**/*.java'

      - uses: axel-op/googlejavaformat-action@v3.6.0
        if: ${{ steps.changes.outputs.android-java == 'true' }}
        with:
          files: "android/src/**/*.java"
          args: "-r -a"
          skipCommit: false

      - if: ${{ steps.changes.outputs.c-src == 'true' }}
        run: |
          sudo apt-get install -y clang-format
          echo ${{ steps.changes.outputs.c-src_files }} | xargs -n 1 clang-format -i

      - name: Setup Java 23
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v3

      - name: Push
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          git add .
          git commit -m "Update files"
          git push

      - run: gradle :core:test

  android:
    runs-on: ubuntu-latest
    needs: [core]
    if: ${{ needs.core.outputs.android == 'true' }}
    steps:

      - uses: actions/checkout@v4.1.1

      - name: Setup Java 23
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v3

      - run: gradle :android:build -Prelease

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: APK
          path: ${{ github.workspace }}/android/build/outputs/apk/release/android-release.apk

